### PR TITLE
BCPT: Added stacktrace for errored interaction

### LINKED ISSUE #382: [BC Idea]: Add alStackTrace to BCPT
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=91d6c614-9a8e-ee11-a81c-00224852ae57

### Description

People forgot to add the stacktrace in Telemetry:
image

I'd like to create a PR for this:
image

### PR DESCRIPTION
**Pull request by waldo1001**
#### Work Item(s) 
Fixes #382 and #381
<br /><br />Internal work item: AB#492609

### CODE REVIEW

**Review by JesperSchulz — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Looks like you included the changes from #383 as well. I'd suggest to abandon #383 and to link this PR to both your logged issues.

**Comment by waldo1001** [comment]
> Looks like you included the changes from #383 as well. I'd suggest to abandon #383 and to link this PR to both your logged issues.

Oh .. I see where I messed up.  Forgot to branch the first fix - and branched the second based on the first.  That doesn't work.  My apologies :(.

**Comment by JesperSchulz** [comment]
No worries. Now let's get this in!

**Comment by waldo1001** [comment]
A good start is to approve #382, apparently - seems I skipped some steps ;-)

image

**Review by henrikfrovst — APPROVED** [review]

**Pull request merged**
