### PR TITLE
Sharepoint SetXHttpMethod should set data to global variable. Cleanup

### LINKED ISSUE #666: [Bug]: GetXHttpMethod returns no value in 9107 "SharePoint Http Content"
### Describe the issue

The codeunit 9107 "SharePoint Http Content" contains a setter / getter functions for XHttpMethod.

However, the SetXHttpMethod does not properly set the value, resulting in GetXHttpMethod returning an empty value.

### Expected behavior

```
procedure SetXHttpMethod(XHttpMethodValue: Text)
    begin
        XHttpMethodValue := XHttpMethodValue;
    end;
```

should be changed by

```
procedure SetXHttpMethod(XHttpMethodValue: Text)
    begin
        XHttpMethod:= XHttpMethodValue;
    end;
```

resulting in GetXHttpMethod returning the correct value

```
procedure GetXHttpMethod(): Text;
    begin
        exit(XHttpMethod);
    end;
```

### Steps to reproduce

- Call SharePointHttpContent.SetXHttpMethod('MERGE'); 
- SharePointRequestHelper.Post(SharePointUriBuilder, SharePointHttpContent);

Below code does not add a X-HTTP-Method header ...
```
if SharePointHttpContent.GetXHttpMethod() <> '' then
            Headers.Add('X-HTTP-Method', SharePointHttpContent.GetXHttpMethod());
```

### Additional context

I can provide a fix, but have no time to write any tests

### I will provide a fix for a bug

- [ ] I will provide a fix for a bug

### PR DESCRIPTION
**Pull request by Drakonian**
#### Summary 
Sharepoint SetXHttpMethod should set data to global variable. Cleanup
#### Work Item(s) 
Fixes #666 

Fixes [AB#532990](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/532990)

### CODE REVIEW

**Comment by JesperSchulz** [comment]
Looks like you've got an unused variable. Let's make CI pass before we involve developers in the review 🙂

**Comment by Drakonian** [comment]
> Looks like you've got an unused variable. Let's make CI pass before we involve developers in the review 🙂

How do you do that? I thought CI process starts only after assigning an internal ticket number

**Comment by Drakonian** [comment]
@JesperSchulz 
I mean, can I run CI myself to make sure everything is ready? :)

**Comment by Drakonian** [comment]
Fixed

**Comment by Drakonian** [comment]
> > > Looks like you've got an unused variable. Let's make CI pass before we involve developers in the review 🙂
> > 
> > 
> > How I can do that? I thought CI process starts only after assigning an internal ticket number
> 
> I can kick off the CI process any time. Will do so again to see if it passes now 🙂

I would of course like to run CI at least locally before send code -)

This error looks like an internal

image

**Comment by JesperSchulz** [comment]
Let's try this once more, before I bring in the cavalry...

**Comment by JesperSchulz** [comment]
@Drakonian, now there actually seem to be real compilation issues (e.g. AL0126 No overload for method 'UpdateListItemMetaDataField' takes 4 arguments.). Could you take another look?

**Comment by Drakonian** [comment]
@JesperSchulz fixed

**Comment by JesperSchulz** [comment]
All CI checks have passed. Now we'll review 🚀

**Review by JesperSchulz — APPROVED** [review]

**Review by darjoo — APPROVED** [review]

**Pull request merged**
